# Generated by Django 5.2.1 on 2025-06-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedimage',
            name='name',
            field=models.CharField(default='untitled_image', max_length=255),
        ),
    ]
