# Generated by Django 5.2.3 on 2025-06-17 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_savedimage_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='savedimage',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_image_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='savedimage',
            constraint=models.UniqueConstraint(fields=('user', 'image_url'), name='unique_image_url_per_user'),
        ),
    ]
