# Generated by Django 5.2.3 on 2025-06-17 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_remove_savedimage_unique_image_name_per_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedimage',
            name='image_hash',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name='savedimage',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_image_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='savedimage',
            constraint=models.UniqueConstraint(fields=('user', 'image_hash'), name='unique_image_hash_per_user'),
        ),
    ]
