# Generated by Django 5.2.3 on 2025-06-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_savedimage_image_hash_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='savedimage',
            name='unique_image_name_per_user',
        ),
    ]
